title: My Test Blog
author: Tom Twig
email: -
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  some random lorum ipsum description. No search-engine will ever find it.
  


# social links
github_username:  TomTwig

